# Generated by Django 2.2.1 on 2020-05-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.CharField(max_length=10, unique=True)),
                ('floor_no', models.IntegerField(max_length=10)),
                ('floor_name', models.CharField(max_length=10)),
                ('facility_id_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Facility')),
            ],
        ),
    ]
