# Generated by Django 2.2.1 on 2020-05-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorid', models.CharField(max_length=10, unique=True)),
                ('sectorname', models.CharField(max_length=15)),
                ('floorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Floor')),
            ],
        ),
    ]
