# Generated by Django 2.2.1 on 2020-05-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200515_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='facility_id_FK',
            new_name='facility_id',
        ),
    ]
