# Generated by Django 2.2.1 on 2020-05-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200515_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='facility_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_details', to='webapp.Facility'),
        ),
    ]
