# Generated by Django 2.2.1 on 2020-05-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200515_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='Facility_id',
            new_name='facility_id',
        ),
    ]
