# Generated by Django 2.2.1 on 2020-05-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200515_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='facility_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='webapp.Facility'),
        ),
    ]
