# Generated by Django 2.2.1 on 2020-05-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200515_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='facility_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_floors', to='webapp.Facility'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorid', models.IntegerField()),
                ('sectorname', models.CharField(max_length=15)),
                ('floorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_secotrs', to='webapp.Floor')),
            ],
        ),
    ]
